<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>TorrWind</AssemblyName>
    <RootNamespace>TorrWind.App</RootNamespace>
    <ApplicationIcon>..\..\assets\TorrWind.ico</ApplicationIcon>
    <VlcWindowsX64Enabled>true</VlcWindowsX64Enabled>
    <VlcWindowsX86Enabled>false</VlcWindowsX86Enabled>
    <VlcWindowsArm64Enabled>false</VlcWindowsArm64Enabled>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TorrWind.Core\TorrWind.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\locales\**\*.json" CopyToOutputDirectory="PreserveNewest" LinkBase="locales" />
    <Resource Include="..\..\assets\TorrWind.ico" Link="TorrWind.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4022.49" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
  </ItemGroup>
</Project>
